# docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  wikijs:
    build:
      context: ./wiki
    command: yarn dev
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - DB_TYPE
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_SSL
      - UPGRADE_EXTENSIONS
      - WIKI_SHARED_SECRET
      - LOG_LEVEL
      - DEBUG
      - NODE_ENV
      - LOGIN_REDIRECT_URL
    depends_on:
      - postgres
    volumes:
      - ./wiki:/wiki

volumes:
  pgdata:
  wikijs_node_modules:
