# Étape 1 – Build assets
FROM node:18-alpine AS build

WORKDIR /wiki

RUN apk add --no-cache git python3 make g++ bash curl jq
RUN jq '.dev = false' package.json > tmp.json && mv tmp.json package.json

COPY . .

RUN yarn install
RUN yarn build
RUN yarn --production --frozen-lockfile --non-interactive

# Étape 2 – Image finale
FROM node:18-alpine

RUN apk add --no-cache bash curl git sqlite

WORKDIR /wiki

COPY --from=build /wiki ./

EXPOSE 3000 3443
CMD ["node", "server"]