# Dockerfile.dev
FROM node:18-alpine

RUN apk add --no-cache \
    git \
    python3 \
    make \
    g++ \
    bash \
    curl

WORKDIR /wiki

COPY package.json yarn.lock ./
RUN yarn install --production

COPY server ./server
COPY config.yml ./
COPY LICENSE package.json ./

EXPOSE 3000

CMD ["node", "--trace-deprecation", "server"]